cmake_minimum_required(VERSION 3.18)
project(mathic-consumer LANGUAGES CXX)
find_package(mathic 1.5 CONFIG REQUIRED)
add_executable(consumer consumer.cpp)
target_link_libraries(consumer PRIVATE mathic::mathic)
if(EXPECT_DEBUG)
  target_compile_definitions(consumer PRIVATE EXPECT_DEBUG)
endif()
enable_testing()
add_test(NAME installed-consumer COMMAND consumer)
